{
  "name": "failing-line",
  "version": "0.1.0",
  "description": "Return the line number and filename of failing line from given error object",
  "main": "index.js",
  "scripts": {
    "test": "node test.js"
  },
  "devDependencies": {
    "tape": "*"
  },
  "keywords": [
    "error",
    "fail",
    "failing",
    "line number"
  ],
  "repository": {
    "url": "git@github.com:azer/failing-line.git",
    "type": "git"
  },
  "author": "azer",
  "license": "BSD",
  "_id": "failing-line@0.1.0",
  "_npmVersion": "0.0.0-fake",
  "_nodeVersion": "0.0.0-fake",
  "_shasum": "fc14fd8f0801a641f1144e4e893010ab6fea2496",
  "_npmUser": {
    "name": "npm",
    "email": "support@npmjs.com"
  },
  "_from": "failing-line@>=0.1.0 <0.2.0",
  "dist": {
    "shasum": "fc14fd8f0801a641f1144e4e893010ab6fea2496",
    "tarball": "https://registry.npmjs.org/failing-line/-/failing-line-0.1.0.tgz"
  },
  "maintainers": [
    {
      "name": "npm",
      "email": "npm@npmjs.com"
    }
  ],
  "directories": {},
  "_resolved": "https://registry.npmjs.org/failing-line/-/failing-line-0.1.0.tgz"
}
